ARG BASE_IMAGE=vllm/vllm-openai:v0.12.0
FROM ${BASE_IMAGE}

WORKDIR /vllm-workspace

RUN apt-get update \
    && apt-get install -y git curl wget \
    && apt-get install -y net-tools netcat-openbsd \
    && apt-get install -y rdma-core ibverbs-utils kmod

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

# Clone vllm
RUN git clone -b releases/v0.12.0 https://github.com/vllm-project/vllm.git /tmp/vllm/

# Copy and apply patch, then install vllm
COPY ./patches/vllm/vllm_v0.12.0.patch /tmp/
RUN cd /tmp/vllm \
    && export VLLM_PRECOMPILED_WHEEL_COMMIT=$(git rev-parse HEAD) \
    && export VLLM_USE_PRECOMPILED=1 \
    && patch -p1 < /tmp/vllm_v0.12.0.patch \
    && pip install . --no-deps --no-build-isolation -v \
    && rm -rf /tmp/vllm

# Install llumnix python package
COPY ./python/llumnix/dist/ /tmp/llumnix_whl/
RUN cd /tmp/llumnix_whl \
    && WHL_FILE=$(ls llumnix-*.whl) \
    && pip install "${WHL_FILE}[vllm]" \
    && rm -rf /tmp/llumnix_whl
COPY ./patches/vllm/mooncake/mooncake_connector_v1.py /usr/local/lib/python3.12/dist-packages/mooncake/mooncake_connector_v1.py

# Set CUDA environment variables
ENV CUDA_HOME=/usr/local/cuda \
    CUDA_PATH=/usr/local/cuda \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH \
    PATH=/usr/local/cuda/bin:$PATH 

# Install blade-kvt
COPY ./scripts/install/install_barex.sh /tmp/install_barex.sh
RUN bash /tmp/install_barex.sh
COPY ./lib/blade_kvt-*.whl /tmp/
RUN pip install /tmp/blade_kvt-*.whl

# Build mooncake from source
RUN pip uninstall -y mooncake-transfer-engine
RUN git clone https://github.com/kvcache-ai/Mooncake.git /tmp/Mooncake/
COPY ./scripts/install/install_go.sh /tmp/install_go.sh
RUN bash /tmp/install_go.sh
ENV PATH="/usr/local/go/bin:${PATH}"
RUN cd /tmp/Mooncake \
    && bash dependencies.sh \
    && rm -rf build && mkdir build \
    && cd build \
    && cmake .. \
        -DPython_EXECUTABLE=/usr/bin/python3.12 \
        -DPython3_EXECUTABLE=/usr/bin/python3.12 \
        -DPython_INCLUDE_DIR=/usr/include/python3.12 \
        -DPython_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.12.so \
        -DPython3_INCLUDE_DIR=/usr/include/python3.12 \
        -DPython3_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.12.so \
    && make -j \
    && make install \
    && rm -rf /tmp/Mooncake

# Install erdma
RUN apt-get install -y wget \
    && cd /tmp \
    && wget -O erdma_installer.tar.gz http://mirrors.cloud.aliyuncs.com/erdma/erdma_installer-1.4.5.tar.gz \
    && tar xzf erdma_installer.tar.gz \
    && dpkg -i --force-overwrite erdma_installer/DEBS/ubuntu22/x86_64/{rdma-core,libibverbs1,ibverbs-providers,ibverbs-utils,librdmacm1,libibumad3}_*.deb \
    && rm -rf /tmp/erdma_installer /tmp/erdma_installer.tar.gz

RUN apt-get clean && rm -rf /var/lib/apt/lists/*