ARG BASE_IMAGE=vllm/vllm-openai:v0.12.0
FROM ${BASE_IMAGE}

WORKDIR /vllm-workspace

RUN apt-get update && apt-get install -y git curl wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

# Clone vllm
RUN git clone -b releases/v0.12.0 https://github.com/vllm-project/vllm.git /tmp/vllm/

# Copy and apply patch, then install vllm
COPY ./patches/vllm/vllm_v0.12.0.patch /tmp/
RUN cd /tmp/vllm \
    && export VLLM_PRECOMPILED_WHEEL_COMMIT=$(git rev-parse HEAD) \
    && export VLLM_USE_PRECOMPILED=1 \
    && patch -p1 < /tmp/vllm_v0.12.0.patch \
    && pip install . --no-deps --no-build-isolation -v \
    && rm -rf /tmp/vllm

# Install llumnix python package
COPY ./python/llumnix/dist/ /tmp/llumnix_whl/
RUN cd /tmp/llumnix_whl \
    && WHL_FILE=$(ls llumnix-*.whl) \
    && pip install "${WHL_FILE}[vllm]" \
    && rm -rf /tmp/llumnix_whl
COPY ./patches/vllm/mooncake/mooncake_connector_v1.py /usr/local/lib/python3.12/dist-packages/mooncake/mooncake_connector_v1.py
