FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates git curl wget \
    && rm -rf /var/lib/apt/lists/*

COPY ./bin/gateway /usr/local/bin/gateway

COPY ./lib/sglang/sgl-model-gateway/bindings/golang/target/release/*.a /usr/lib

WORKDIR /gateway
