ARG BASE_IMAGE=vllm/vllm-openai:v0.12.0
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y git curl wget protobuf-compiler vim pkg-config libssl-dev apt-transport-https ca-certificates redis-server

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

# Apply vllm patch and install
COPY ./python/llumnix/patches/vllm/vllm_v0.12.0.patch /tmp/
RUN git clone -b releases/v0.12.0 https://github.com/vllm-project/vllm.git /tmp/vllm/ \
    && cd /tmp/vllm \
    && export VLLM_PRECOMPILED_WHEEL_COMMIT=$(git rev-parse HEAD) \
    && export VLLM_USE_PRECOMPILED=1 \
    && patch -p1 < /tmp/vllm_v0.12.0.patch \
    && pip install . --no-deps --no-build-isolation -v \
    && rm -rf /tmp/vllm \
    && rm /tmp/vllm_v0.12.0.patch

# Install llumnix python package
COPY ./python/llumnix/requirements /tmp/requirements
RUN  pip install -r /tmp/requirements/vllm.txt -r /tmp/requirements/common.txt \
    && rm -rf /tmp/requirements
COPY ./python/llumnix/patches/vllm/mooncake/mooncake_connector_v1.py /usr/local/lib/python3.12/dist-packages/mooncake/mooncake_connector_v1.py

# Install rust (Used for building tokenizer library)
RUN export RUSTUP_DIST_SERVER="https://rsproxy.cn" \
    && export RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup" \
    && curl --proto '=https' --tlsv1.2 -sSf https://rsproxy.cn/rustup-init.sh | sh -s -- -y \
    && . /root/.cargo/env \
    && rustup self update \
    && rustup update stable \
    && mkdir -p /root/.cargo \
    && cat > /root/.cargo/config.toml <<'EOF'
[source.crates-io]
replace-with = 'rsproxy-sparse'

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "sparse+https://rsproxy.cn/index/"

[net]
git-fetch-with-cli = true
EOF

# Install golang
RUN wget https://golang.google.cn/dl/go1.23.0.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz \
    && rm go1.23.0.linux-amd64.tar.gz
ENV GOROOT=/usr/local/go
ENV GOPATH=/root/go
ENV GOPROXY=https://goproxy.io,direct
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.5 \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

# vscode can't set go env, so we need to set it manually
RUN echo 'export GOROOT=/usr/local/go' >> ~/.bashrc && \
    echo 'export GOPATH=/root/go' >> ~/.bashrc && \
    echo 'export GOPROXY=https://goproxy.io,direct' >> ~/.bashrc && \
    echo 'export PATH=$PATH:/usr/local/go/bin:/root/go/bin' >> ~/.bashrc

# Install go requirements
COPY . /tmp/llumnix_go/
RUN cd /tmp/llumnix_go && GOPROXY=https://goproxy.cn,direct go mod download \
    && rm -rf /tmp/llumnix_go

# Install kubectl
RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg \
    && echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list \
    && apt-get update \
    && apt-get install -y kubectl

ENTRYPOINT [ "" ]

WORKDIR /app
