# Ref: https://aliyuque.antfin.com/alicode/docs/btevdryaniom98ry
name: '[Llumnix] Pylint'

triggers:
  push:
    branches:
      - 'release/**'
      - 'dev'
  merge_request:
    target-branches:
      - '**'

jobs:
  pylint:
    timeout: 5m
    runs-on:
      - amd64
      - linux
    image: "alios-8u"
    steps:
      - uses: setup-env
        inputs:
          python-version: '3.10'
      - uses: checkout
      - run: |
          make lint
