apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: GROUP_NAME_PLACEHOLDER-nas
    group: GROUP_NAME_PLACEHOLDER
  name: GROUP_NAME_PLACEHOLDER-nas
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Ti
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: /models
      server: 0110c568-a894.cn-beijing.extreme.nas.aliyuncs.com
    volumeHandle: GROUP_NAME_PLACEHOLDER-nas
  mountOptions:
    - 'nolock,tcp,noresvport'
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
