apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: nas-llumnix
  namespace: GROUP_NAME_PLACEHOLDER
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      alicloud-pvname: GROUP_NAME_PLACEHOLDER-nas
      group: GROUP_NAME_PLACEHOLDER
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: GROUP_NAME_PLACEHOLDER-nas