// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: llm-gateway/resolver/proto/redis_discovery.proto

package resolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodDiscoveryInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PodName       string                   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	TimestampMs   int64                    `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Instances     []*InstanceDiscoveryInfo `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodDiscoveryInfo) Reset() {
	*x = PodDiscoveryInfo{}
	mi := &file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodDiscoveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDiscoveryInfo) ProtoMessage() {}

func (x *PodDiscoveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDiscoveryInfo.ProtoReflect.Descriptor instead.
func (*PodDiscoveryInfo) Descriptor() ([]byte, []int) {
	return file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *PodDiscoveryInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodDiscoveryInfo) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *PodDiscoveryInfo) GetInstances() []*InstanceDiscoveryInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceDiscoveryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Role           string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // prefill, decode or normal
	EntrypointIp   string                 `protobuf:"bytes,2,opt,name=entrypoint_ip,json=entrypointIp,proto3" json:"entrypoint_ip,omitempty"`
	EntrypointPort int32                  `protobuf:"varint,3,opt,name=entrypoint_port,json=entrypointPort,proto3" json:"entrypoint_port,omitempty"`
	KvTransferIp   string                 `protobuf:"bytes,4,opt,name=kv_transfer_ip,json=kvTransferIp,proto3" json:"kv_transfer_ip,omitempty"`
	KvTransferPort int32                  `protobuf:"varint,5,opt,name=kv_transfer_port,json=kvTransferPort,proto3" json:"kv_transfer_port,omitempty"`
	DpRank         int32                  `protobuf:"varint,6,opt,name=dp_rank,json=dpRank,proto3" json:"dp_rank,omitempty"`
	DpSize         int32                  `protobuf:"varint,7,opt,name=dp_size,json=dpSize,proto3" json:"dp_size,omitempty"`
	Model          string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	Version        int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceDiscoveryInfo) Reset() {
	*x = InstanceDiscoveryInfo{}
	mi := &file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceDiscoveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceDiscoveryInfo) ProtoMessage() {}

func (x *InstanceDiscoveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceDiscoveryInfo.ProtoReflect.Descriptor instead.
func (*InstanceDiscoveryInfo) Descriptor() ([]byte, []int) {
	return file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceDiscoveryInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InstanceDiscoveryInfo) GetEntrypointIp() string {
	if x != nil {
		return x.EntrypointIp
	}
	return ""
}

func (x *InstanceDiscoveryInfo) GetEntrypointPort() int32 {
	if x != nil {
		return x.EntrypointPort
	}
	return 0
}

func (x *InstanceDiscoveryInfo) GetKvTransferIp() string {
	if x != nil {
		return x.KvTransferIp
	}
	return ""
}

func (x *InstanceDiscoveryInfo) GetKvTransferPort() int32 {
	if x != nil {
		return x.KvTransferPort
	}
	return 0
}

func (x *InstanceDiscoveryInfo) GetDpRank() int32 {
	if x != nil {
		return x.DpRank
	}
	return 0
}

func (x *InstanceDiscoveryInfo) GetDpSize() int32 {
	if x != nil {
		return x.DpSize
	}
	return 0
}

func (x *InstanceDiscoveryInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InstanceDiscoveryInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_llm_gateway_resolver_proto_redis_discovery_proto protoreflect.FileDescriptor

const file_llm_gateway_resolver_proto_redis_discovery_proto_rawDesc = "" +
	"\n" +
	"0llm-gateway/resolver/proto/redis_discovery.proto\x12\bresolver\"\x8f\x01\n" +
	"\x10PodDiscoveryInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12=\n" +
	"\tinstances\x18\x04 \x03(\v2\x1f.resolver.InstanceDiscoveryInfoR\tinstances\"\xab\x02\n" +
	"\x15InstanceDiscoveryInfo\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12#\n" +
	"\rentrypoint_ip\x18\x02 \x01(\tR\fentrypointIp\x12'\n" +
	"\x0fentrypoint_port\x18\x03 \x01(\x05R\x0eentrypointPort\x12$\n" +
	"\x0ekv_transfer_ip\x18\x04 \x01(\tR\fkvTransferIp\x12(\n" +
	"\x10kv_transfer_port\x18\x05 \x01(\x05R\x0ekvTransferPort\x12\x17\n" +
	"\adp_rank\x18\x06 \x01(\x05R\x06dpRank\x12\x17\n" +
	"\adp_size\x18\a \x01(\x05R\x06dpSize\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversionB\rZ\v./;resolverb\x06proto3"

var (
	file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescOnce sync.Once
	file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescData []byte
)

func file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescGZIP() []byte {
	file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescOnce.Do(func() {
		file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_gateway_resolver_proto_redis_discovery_proto_rawDesc), len(file_llm_gateway_resolver_proto_redis_discovery_proto_rawDesc)))
	})
	return file_llm_gateway_resolver_proto_redis_discovery_proto_rawDescData
}

var file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llm_gateway_resolver_proto_redis_discovery_proto_goTypes = []any{
	(*PodDiscoveryInfo)(nil),      // 0: resolver.PodDiscoveryInfo
	(*InstanceDiscoveryInfo)(nil), // 1: resolver.InstanceDiscoveryInfo
}
var file_llm_gateway_resolver_proto_redis_discovery_proto_depIdxs = []int32{
	1, // 0: resolver.PodDiscoveryInfo.instances:type_name -> resolver.InstanceDiscoveryInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_llm_gateway_resolver_proto_redis_discovery_proto_init() }
func file_llm_gateway_resolver_proto_redis_discovery_proto_init() {
	if File_llm_gateway_resolver_proto_redis_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_gateway_resolver_proto_redis_discovery_proto_rawDesc), len(file_llm_gateway_resolver_proto_redis_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_gateway_resolver_proto_redis_discovery_proto_goTypes,
		DependencyIndexes: file_llm_gateway_resolver_proto_redis_discovery_proto_depIdxs,
		MessageInfos:      file_llm_gateway_resolver_proto_redis_discovery_proto_msgTypes,
	}.Build()
	File_llm_gateway_resolver_proto_redis_discovery_proto = out.File
	file_llm_gateway_resolver_proto_redis_discovery_proto_goTypes = nil
	file_llm_gateway_resolver_proto_redis_discovery_proto_depIdxs = nil
}
