apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    role: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    role: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        role: gateway
    spec:
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
      - name: aliyun-registry-secret
      containers:
      - name: gateway
        image: beijing-pooling-registry-vpc.cn-beijing.cr.aliyuncs.com/llumnix/llumnix-dev:gateway-20260116-001948
        imagePullPolicy: Always
        command: ["/usr/local/bin/llm-gateway"]
        args:
        - "--port"
        - "8089"
        - "-v"
        - "4"
        - "--llm-scheduler"
        - "llumnix-scheduler"
        - "--use-discovery"
        - "redis"
        - "--llumnix-cms-redis-host"
        - "redis"
        - "--llumnix-cms-redis-port"
        - "6379"
        - "--schedule-policy"
        # - "least-token"
        - "round-robin"
        - "--local-test-scheduler-ip"
        - "scheduler:8088"
        - "--llumnix-kv-cache-block-size"
        - "64"
        - "--tokenizer-name"
        - "DeepSeek-R1-0528"
        # - "--pdsplit-mode"
        # - "vllm-mooncake"
        - "--enable-full-mode-scheduling"
        - "True"
        ports:
        - containerPort: 8089
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5
#        lifecycle:
#          preStop:
#            exec:
#              command:
#              - /bin/sh
#              - -c
#              - |
#                echo "Gateway is shutting down, waiting 180 seconds for debugging..."
#                sleep 180