apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: GROUP_NAME_PLACEHOLDER-oss-llm-cache
    group: GROUP_NAME_PLACEHOLDER
  name: GROUP_NAME_PLACEHOLDER-oss-llm-cache
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 500Gi
  csi:
    driver: ossplugin.csi.alibabacloud.com
    nodePublishSecretRef:
      name: aksk
      namespace: default
    volumeAttributes:
      bucket: llm-cache
      otherOpts: ''
      url: oss-cn-beijing-internal.aliyuncs.com
    volumeHandle: GROUP_NAME_PLACEHOLDER-oss-llm-cache
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oss
  volumeMode: Filesystem
