apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  name: oss-llm-cache
  namespace: GROUP_NAME_PLACEHOLDER
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      alicloud-pvname: GROUP_NAME_PLACEHOLDER-oss-llm-cache
      group: GROUP_NAME_PLACEHOLDER
  storageClassName: oss
  volumeMode: Filesystem
  volumeName: GROUP_NAME_PLACEHOLDER-oss-llm-cache
