// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: llm-gateway/cms/proto/cms.proto

package cms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// engine meta
	InstanceId   string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceType string `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	BackendType  string `protobuf:"bytes,3,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	// hardware meta
	Ip            string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	IpKvs         string `protobuf:"bytes,5,opt,name=ip_kvs,json=ipKvs,proto3" json:"ip_kvs,omitempty"`
	ApiServerPort int32  `protobuf:"varint,6,opt,name=api_server_port,json=apiServerPort,proto3" json:"api_server_port,omitempty"`
	LlumletPort   int32  `protobuf:"varint,7,opt,name=llumlet_port,json=llumletPort,proto3" json:"llumlet_port,omitempty"`
	KvtPort       int32  `protobuf:"varint,8,opt,name=kvt_port,json=kvtPort,proto3" json:"kvt_port,omitempty"`
	NodeId        string `protobuf:"bytes,9,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// parallel meta
	DataParallelSize   int32   `protobuf:"varint,10,opt,name=data_parallel_size,json=dataParallelSize,proto3" json:"data_parallel_size,omitempty"`
	TensorParallelSize int32   `protobuf:"varint,11,opt,name=tensor_parallel_size,json=tensorParallelSize,proto3" json:"tensor_parallel_size,omitempty"`
	UnitId             string  `protobuf:"bytes,12,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	DpRank             int32   `protobuf:"varint,13,opt,name=dp_rank,json=dpRank,proto3" json:"dp_rank,omitempty"`
	EpRank             int32   `protobuf:"varint,14,opt,name=ep_rank,json=epRank,proto3" json:"ep_rank,omitempty"`
	DpLocalRank        int32   `protobuf:"varint,15,opt,name=dp_local_rank,json=dpLocalRank,proto3" json:"dp_local_rank,omitempty"`
	UtcCreate          float64 `protobuf:"fixed64,16,opt,name=utc_create,json=utcCreate,proto3" json:"utc_create,omitempty"`
	UtcUpdate          float64 `protobuf:"fixed64,17,opt,name=utc_update,json=utcUpdate,proto3" json:"utc_update,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstanceMetadata) Reset() {
	*x = InstanceMetadata{}
	mi := &file_llm_gateway_cms_proto_cms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMetadata) ProtoMessage() {}

func (x *InstanceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_cms_proto_cms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMetadata.ProtoReflect.Descriptor instead.
func (*InstanceMetadata) Descriptor() ([]byte, []int) {
	return file_llm_gateway_cms_proto_cms_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceMetadata) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceMetadata) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *InstanceMetadata) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *InstanceMetadata) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InstanceMetadata) GetIpKvs() string {
	if x != nil {
		return x.IpKvs
	}
	return ""
}

func (x *InstanceMetadata) GetApiServerPort() int32 {
	if x != nil {
		return x.ApiServerPort
	}
	return 0
}

func (x *InstanceMetadata) GetLlumletPort() int32 {
	if x != nil {
		return x.LlumletPort
	}
	return 0
}

func (x *InstanceMetadata) GetKvtPort() int32 {
	if x != nil {
		return x.KvtPort
	}
	return 0
}

func (x *InstanceMetadata) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstanceMetadata) GetDataParallelSize() int32 {
	if x != nil {
		return x.DataParallelSize
	}
	return 0
}

func (x *InstanceMetadata) GetTensorParallelSize() int32 {
	if x != nil {
		return x.TensorParallelSize
	}
	return 0
}

func (x *InstanceMetadata) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *InstanceMetadata) GetDpRank() int32 {
	if x != nil {
		return x.DpRank
	}
	return 0
}

func (x *InstanceMetadata) GetEpRank() int32 {
	if x != nil {
		return x.EpRank
	}
	return 0
}

func (x *InstanceMetadata) GetDpLocalRank() int32 {
	if x != nil {
		return x.DpLocalRank
	}
	return 0
}

func (x *InstanceMetadata) GetUtcCreate() float64 {
	if x != nil {
		return x.UtcCreate
	}
	return 0
}

func (x *InstanceMetadata) GetUtcUpdate() float64 {
	if x != nil {
		return x.UtcUpdate
	}
	return 0
}

type InstanceStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// step loop status
	Schedulable bool  `protobuf:"varint,2,opt,name=schedulable,proto3" json:"schedulable,omitempty"`
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	StepId      int32 `protobuf:"varint,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	UpdateId    int32 `protobuf:"varint,5,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// status for updating instance status local account
	RecentWaitingRequests []string `protobuf:"bytes,6,rep,name=recent_waiting_requests,json=recentWaitingRequests,proto3" json:"recent_waiting_requests,omitempty"`
	WaitingRequests       []string `protobuf:"bytes,7,rep,name=waiting_requests,json=waitingRequests,proto3" json:"waiting_requests,omitempty"`
	// num requests status
	HybridSchedulerWaitingToDecodeRequestsNum int32 `protobuf:"varint,8,opt,name=hybrid_scheduler_waiting_to_decode_requests_num,json=hybridSchedulerWaitingToDecodeRequestsNum,proto3" json:"hybrid_scheduler_waiting_to_decode_requests_num,omitempty"`
	SchedulerWaitingToDecodeRequestsNum       int32 `protobuf:"varint,9,opt,name=scheduler_waiting_to_decode_requests_num,json=schedulerWaitingToDecodeRequestsNum,proto3" json:"scheduler_waiting_to_decode_requests_num,omitempty"`
	NumWaitingRequests                        int32 `protobuf:"varint,10,opt,name=num_waiting_requests,json=numWaitingRequests,proto3" json:"num_waiting_requests,omitempty"`
	SchedulerRunningToDecodeRequestsNum       int32 `protobuf:"varint,11,opt,name=scheduler_running_to_decode_requests_num,json=schedulerRunningToDecodeRequestsNum,proto3" json:"scheduler_running_to_decode_requests_num,omitempty"`
	NumRunningRequests                        int32 `protobuf:"varint,12,opt,name=num_running_requests,json=numRunningRequests,proto3" json:"num_running_requests,omitempty"`
	NumLoadingRequests                        int32 `protobuf:"varint,13,opt,name=num_loading_requests,json=numLoadingRequests,proto3" json:"num_loading_requests,omitempty"`
	// num blocks status from kv manager
	NumTotalGpuBlocks int32 `protobuf:"varint,14,opt,name=num_total_gpu_blocks,json=numTotalGpuBlocks,proto3" json:"num_total_gpu_blocks,omitempty"`
	NumUsedGpuBlocks  int32 `protobuf:"varint,15,opt,name=num_used_gpu_blocks,json=numUsedGpuBlocks,proto3" json:"num_used_gpu_blocks,omitempty"`
	// num blocks status from scheduler and hybrid scheduler
	NumUncomputedBlocksHybridSchedulerWaitingPrefills int32 `protobuf:"varint,16,opt,name=num_uncomputed_blocks_hybrid_scheduler_waiting_prefills,json=numUncomputedBlocksHybridSchedulerWaitingPrefills,proto3" json:"num_uncomputed_blocks_hybrid_scheduler_waiting_prefills,omitempty"`
	NumUnallocatedBlocksHybridSchedulerWaitingDecodes int32 `protobuf:"varint,17,opt,name=num_unallocated_blocks_hybrid_scheduler_waiting_decodes,json=numUnallocatedBlocksHybridSchedulerWaitingDecodes,proto3" json:"num_unallocated_blocks_hybrid_scheduler_waiting_decodes,omitempty"`
	HybridSchedulerWaitingToDecodeBlocksNum           int32 `protobuf:"varint,18,opt,name=hybrid_scheduler_waiting_to_decode_blocks_num,json=hybridSchedulerWaitingToDecodeBlocksNum,proto3" json:"hybrid_scheduler_waiting_to_decode_blocks_num,omitempty"`
	NumUncomputedBlocksSchedulerWaitingPrefills       int32 `protobuf:"varint,19,opt,name=num_uncomputed_blocks_scheduler_waiting_prefills,json=numUncomputedBlocksSchedulerWaitingPrefills,proto3" json:"num_uncomputed_blocks_scheduler_waiting_prefills,omitempty"`
	SchedulerWaitingToDecodeBlocksNum                 int32 `protobuf:"varint,20,opt,name=scheduler_waiting_to_decode_blocks_num,json=schedulerWaitingToDecodeBlocksNum,proto3" json:"scheduler_waiting_to_decode_blocks_num,omitempty"`
	NumUncomputedBlocksSchedulerRunningPrefills       int32 `protobuf:"varint,21,opt,name=num_uncomputed_blocks_scheduler_running_prefills,json=numUncomputedBlocksSchedulerRunningPrefills,proto3" json:"num_uncomputed_blocks_scheduler_running_prefills,omitempty"`
	NumUnallocatedBlocksSchedulerRunningPrefills      int32 `protobuf:"varint,22,opt,name=num_unallocated_blocks_scheduler_running_prefills,json=numUnallocatedBlocksSchedulerRunningPrefills,proto3" json:"num_unallocated_blocks_scheduler_running_prefills,omitempty"`
	SchedulerRunningToDecodeBlocksNum                 int32 `protobuf:"varint,23,opt,name=scheduler_running_to_decode_blocks_num,json=schedulerRunningToDecodeBlocksNum,proto3" json:"scheduler_running_to_decode_blocks_num,omitempty"`
	NumBlocksLoadingRequests                          int32 `protobuf:"varint,24,opt,name=num_blocks_loading_requests,json=numBlocksLoadingRequests,proto3" json:"num_blocks_loading_requests,omitempty"`
	NumUncomputedBlocksAllWaitingPrefills             int32 `protobuf:"varint,25,opt,name=num_uncomputed_blocks_all_waiting_prefills,json=numUncomputedBlocksAllWaitingPrefills,proto3" json:"num_uncomputed_blocks_all_waiting_prefills,omitempty"`
	// migration status
	NumMigrateInReqs              int32   `protobuf:"varint,26,opt,name=num_migrate_in_reqs,json=numMigrateInReqs,proto3" json:"num_migrate_in_reqs,omitempty"`
	NumMigrateOutReqs             int32   `protobuf:"varint,27,opt,name=num_migrate_out_reqs,json=numMigrateOutReqs,proto3" json:"num_migrate_out_reqs,omitempty"`
	NumAvailableMigrateInSlots    int32   `protobuf:"varint,28,opt,name=num_available_migrate_in_slots,json=numAvailableMigrateInSlots,proto3" json:"num_available_migrate_in_slots,omitempty"`
	NumAvailableMigrateOutSlots   int32   `protobuf:"varint,29,opt,name=num_available_migrate_out_slots,json=numAvailableMigrateOutSlots,proto3" json:"num_available_migrate_out_slots,omitempty"`
	NumMigrateInTokens            int32   `protobuf:"varint,30,opt,name=num_migrate_in_tokens,json=numMigrateInTokens,proto3" json:"num_migrate_in_tokens,omitempty"`
	NumMigrateOutTokens           int32   `protobuf:"varint,31,opt,name=num_migrate_out_tokens,json=numMigrateOutTokens,proto3" json:"num_migrate_out_tokens,omitempty"`
	NumAvailableMigrateInTokens   int32   `protobuf:"varint,32,opt,name=num_available_migrate_in_tokens,json=numAvailableMigrateInTokens,proto3" json:"num_available_migrate_in_tokens,omitempty"`
	NumAvailableMigrateOutTokens  int32   `protobuf:"varint,33,opt,name=num_available_migrate_out_tokens,json=numAvailableMigrateOutTokens,proto3" json:"num_available_migrate_out_tokens,omitempty"`
	BlockRatioMigrateIn           float64 `protobuf:"fixed64,34,opt,name=block_ratio_migrate_in,json=blockRatioMigrateIn,proto3" json:"block_ratio_migrate_in,omitempty"`
	BlockRatioMigrateOut          float64 `protobuf:"fixed64,35,opt,name=block_ratio_migrate_out,json=blockRatioMigrateOut,proto3" json:"block_ratio_migrate_out,omitempty"`
	AvailableBlockRatioMigrateIn  float64 `protobuf:"fixed64,36,opt,name=available_block_ratio_migrate_in,json=availableBlockRatioMigrateIn,proto3" json:"available_block_ratio_migrate_in,omitempty"`
	AvailableBlockRatioMigrateOut float64 `protobuf:"fixed64,37,opt,name=available_block_ratio_migrate_out,json=availableBlockRatioMigrateOut,proto3" json:"available_block_ratio_migrate_out,omitempty"`
	// profiling status
	ProfilingId               int32   `protobuf:"varint,38,opt,name=profiling_id,json=profilingId,proto3" json:"profiling_id,omitempty"`
	StepDuration              float64 `protobuf:"fixed64,39,opt,name=step_duration,json=stepDuration,proto3" json:"step_duration,omitempty"`
	NumScheduledPrefillTokens int32   `protobuf:"varint,40,opt,name=num_scheduled_prefill_tokens,json=numScheduledPrefillTokens,proto3" json:"num_scheduled_prefill_tokens,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_llm_gateway_cms_proto_cms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_cms_proto_cms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_llm_gateway_cms_proto_cms_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceStatus) GetSchedulable() bool {
	if x != nil {
		return x.Schedulable
	}
	return false
}

func (x *InstanceStatus) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *InstanceStatus) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *InstanceStatus) GetUpdateId() int32 {
	if x != nil {
		return x.UpdateId
	}
	return 0
}

func (x *InstanceStatus) GetRecentWaitingRequests() []string {
	if x != nil {
		return x.RecentWaitingRequests
	}
	return nil
}

func (x *InstanceStatus) GetWaitingRequests() []string {
	if x != nil {
		return x.WaitingRequests
	}
	return nil
}

func (x *InstanceStatus) GetHybridSchedulerWaitingToDecodeRequestsNum() int32 {
	if x != nil {
		return x.HybridSchedulerWaitingToDecodeRequestsNum
	}
	return 0
}

func (x *InstanceStatus) GetSchedulerWaitingToDecodeRequestsNum() int32 {
	if x != nil {
		return x.SchedulerWaitingToDecodeRequestsNum
	}
	return 0
}

func (x *InstanceStatus) GetNumWaitingRequests() int32 {
	if x != nil {
		return x.NumWaitingRequests
	}
	return 0
}

func (x *InstanceStatus) GetSchedulerRunningToDecodeRequestsNum() int32 {
	if x != nil {
		return x.SchedulerRunningToDecodeRequestsNum
	}
	return 0
}

func (x *InstanceStatus) GetNumRunningRequests() int32 {
	if x != nil {
		return x.NumRunningRequests
	}
	return 0
}

func (x *InstanceStatus) GetNumLoadingRequests() int32 {
	if x != nil {
		return x.NumLoadingRequests
	}
	return 0
}

func (x *InstanceStatus) GetNumTotalGpuBlocks() int32 {
	if x != nil {
		return x.NumTotalGpuBlocks
	}
	return 0
}

func (x *InstanceStatus) GetNumUsedGpuBlocks() int32 {
	if x != nil {
		return x.NumUsedGpuBlocks
	}
	return 0
}

func (x *InstanceStatus) GetNumUncomputedBlocksHybridSchedulerWaitingPrefills() int32 {
	if x != nil {
		return x.NumUncomputedBlocksHybridSchedulerWaitingPrefills
	}
	return 0
}

func (x *InstanceStatus) GetNumUnallocatedBlocksHybridSchedulerWaitingDecodes() int32 {
	if x != nil {
		return x.NumUnallocatedBlocksHybridSchedulerWaitingDecodes
	}
	return 0
}

func (x *InstanceStatus) GetHybridSchedulerWaitingToDecodeBlocksNum() int32 {
	if x != nil {
		return x.HybridSchedulerWaitingToDecodeBlocksNum
	}
	return 0
}

func (x *InstanceStatus) GetNumUncomputedBlocksSchedulerWaitingPrefills() int32 {
	if x != nil {
		return x.NumUncomputedBlocksSchedulerWaitingPrefills
	}
	return 0
}

func (x *InstanceStatus) GetSchedulerWaitingToDecodeBlocksNum() int32 {
	if x != nil {
		return x.SchedulerWaitingToDecodeBlocksNum
	}
	return 0
}

func (x *InstanceStatus) GetNumUncomputedBlocksSchedulerRunningPrefills() int32 {
	if x != nil {
		return x.NumUncomputedBlocksSchedulerRunningPrefills
	}
	return 0
}

func (x *InstanceStatus) GetNumUnallocatedBlocksSchedulerRunningPrefills() int32 {
	if x != nil {
		return x.NumUnallocatedBlocksSchedulerRunningPrefills
	}
	return 0
}

func (x *InstanceStatus) GetSchedulerRunningToDecodeBlocksNum() int32 {
	if x != nil {
		return x.SchedulerRunningToDecodeBlocksNum
	}
	return 0
}

func (x *InstanceStatus) GetNumBlocksLoadingRequests() int32 {
	if x != nil {
		return x.NumBlocksLoadingRequests
	}
	return 0
}

func (x *InstanceStatus) GetNumUncomputedBlocksAllWaitingPrefills() int32 {
	if x != nil {
		return x.NumUncomputedBlocksAllWaitingPrefills
	}
	return 0
}

func (x *InstanceStatus) GetNumMigrateInReqs() int32 {
	if x != nil {
		return x.NumMigrateInReqs
	}
	return 0
}

func (x *InstanceStatus) GetNumMigrateOutReqs() int32 {
	if x != nil {
		return x.NumMigrateOutReqs
	}
	return 0
}

func (x *InstanceStatus) GetNumAvailableMigrateInSlots() int32 {
	if x != nil {
		return x.NumAvailableMigrateInSlots
	}
	return 0
}

func (x *InstanceStatus) GetNumAvailableMigrateOutSlots() int32 {
	if x != nil {
		return x.NumAvailableMigrateOutSlots
	}
	return 0
}

func (x *InstanceStatus) GetNumMigrateInTokens() int32 {
	if x != nil {
		return x.NumMigrateInTokens
	}
	return 0
}

func (x *InstanceStatus) GetNumMigrateOutTokens() int32 {
	if x != nil {
		return x.NumMigrateOutTokens
	}
	return 0
}

func (x *InstanceStatus) GetNumAvailableMigrateInTokens() int32 {
	if x != nil {
		return x.NumAvailableMigrateInTokens
	}
	return 0
}

func (x *InstanceStatus) GetNumAvailableMigrateOutTokens() int32 {
	if x != nil {
		return x.NumAvailableMigrateOutTokens
	}
	return 0
}

func (x *InstanceStatus) GetBlockRatioMigrateIn() float64 {
	if x != nil {
		return x.BlockRatioMigrateIn
	}
	return 0
}

func (x *InstanceStatus) GetBlockRatioMigrateOut() float64 {
	if x != nil {
		return x.BlockRatioMigrateOut
	}
	return 0
}

func (x *InstanceStatus) GetAvailableBlockRatioMigrateIn() float64 {
	if x != nil {
		return x.AvailableBlockRatioMigrateIn
	}
	return 0
}

func (x *InstanceStatus) GetAvailableBlockRatioMigrateOut() float64 {
	if x != nil {
		return x.AvailableBlockRatioMigrateOut
	}
	return 0
}

func (x *InstanceStatus) GetProfilingId() int32 {
	if x != nil {
		return x.ProfilingId
	}
	return 0
}

func (x *InstanceStatus) GetStepDuration() float64 {
	if x != nil {
		return x.StepDuration
	}
	return 0
}

func (x *InstanceStatus) GetNumScheduledPrefillTokens() int32 {
	if x != nil {
		return x.NumScheduledPrefillTokens
	}
	return 0
}

var File_llm_gateway_cms_proto_cms_proto protoreflect.FileDescriptor

const file_llm_gateway_cms_proto_cms_proto_rawDesc = "" +
	"\n" +
	"\x1fllm-gateway/cms/proto/cms.proto\x12\x03cms\"\xae\x04\n" +
	"\x10InstanceMetadata\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_type\x18\x02 \x01(\tR\finstanceType\x12!\n" +
	"\fbackend_type\x18\x03 \x01(\tR\vbackendType\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x15\n" +
	"\x06ip_kvs\x18\x05 \x01(\tR\x05ipKvs\x12&\n" +
	"\x0fapi_server_port\x18\x06 \x01(\x05R\rapiServerPort\x12!\n" +
	"\fllumlet_port\x18\a \x01(\x05R\vllumletPort\x12\x19\n" +
	"\bkvt_port\x18\b \x01(\x05R\akvtPort\x12\x17\n" +
	"\anode_id\x18\t \x01(\tR\x06nodeId\x12,\n" +
	"\x12data_parallel_size\x18\n" +
	" \x01(\x05R\x10dataParallelSize\x120\n" +
	"\x14tensor_parallel_size\x18\v \x01(\x05R\x12tensorParallelSize\x12\x17\n" +
	"\aunit_id\x18\f \x01(\tR\x06unitId\x12\x17\n" +
	"\adp_rank\x18\r \x01(\x05R\x06dpRank\x12\x17\n" +
	"\aep_rank\x18\x0e \x01(\x05R\x06epRank\x12\"\n" +
	"\rdp_local_rank\x18\x0f \x01(\x05R\vdpLocalRank\x12\x1d\n" +
	"\n" +
	"utc_create\x18\x10 \x01(\x01R\tutcCreate\x12\x1d\n" +
	"\n" +
	"utc_update\x18\x11 \x01(\x01R\tutcUpdate\"\xbd\x14\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12 \n" +
	"\vschedulable\x18\x02 \x01(\bR\vschedulable\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\x05R\x06stepId\x12\x1b\n" +
	"\tupdate_id\x18\x05 \x01(\x05R\bupdateId\x126\n" +
	"\x17recent_waiting_requests\x18\x06 \x03(\tR\x15recentWaitingRequests\x12)\n" +
	"\x10waiting_requests\x18\a \x03(\tR\x0fwaitingRequests\x12b\n" +
	"/hybrid_scheduler_waiting_to_decode_requests_num\x18\b \x01(\x05R)hybridSchedulerWaitingToDecodeRequestsNum\x12U\n" +
	"(scheduler_waiting_to_decode_requests_num\x18\t \x01(\x05R#schedulerWaitingToDecodeRequestsNum\x120\n" +
	"\x14num_waiting_requests\x18\n" +
	" \x01(\x05R\x12numWaitingRequests\x12U\n" +
	"(scheduler_running_to_decode_requests_num\x18\v \x01(\x05R#schedulerRunningToDecodeRequestsNum\x120\n" +
	"\x14num_running_requests\x18\f \x01(\x05R\x12numRunningRequests\x120\n" +
	"\x14num_loading_requests\x18\r \x01(\x05R\x12numLoadingRequests\x12/\n" +
	"\x14num_total_gpu_blocks\x18\x0e \x01(\x05R\x11numTotalGpuBlocks\x12-\n" +
	"\x13num_used_gpu_blocks\x18\x0f \x01(\x05R\x10numUsedGpuBlocks\x12r\n" +
	"7num_uncomputed_blocks_hybrid_scheduler_waiting_prefills\x18\x10 \x01(\x05R1numUncomputedBlocksHybridSchedulerWaitingPrefills\x12r\n" +
	"7num_unallocated_blocks_hybrid_scheduler_waiting_decodes\x18\x11 \x01(\x05R1numUnallocatedBlocksHybridSchedulerWaitingDecodes\x12^\n" +
	"-hybrid_scheduler_waiting_to_decode_blocks_num\x18\x12 \x01(\x05R'hybridSchedulerWaitingToDecodeBlocksNum\x12e\n" +
	"0num_uncomputed_blocks_scheduler_waiting_prefills\x18\x13 \x01(\x05R+numUncomputedBlocksSchedulerWaitingPrefills\x12Q\n" +
	"&scheduler_waiting_to_decode_blocks_num\x18\x14 \x01(\x05R!schedulerWaitingToDecodeBlocksNum\x12e\n" +
	"0num_uncomputed_blocks_scheduler_running_prefills\x18\x15 \x01(\x05R+numUncomputedBlocksSchedulerRunningPrefills\x12g\n" +
	"1num_unallocated_blocks_scheduler_running_prefills\x18\x16 \x01(\x05R,numUnallocatedBlocksSchedulerRunningPrefills\x12Q\n" +
	"&scheduler_running_to_decode_blocks_num\x18\x17 \x01(\x05R!schedulerRunningToDecodeBlocksNum\x12=\n" +
	"\x1bnum_blocks_loading_requests\x18\x18 \x01(\x05R\x18numBlocksLoadingRequests\x12Y\n" +
	"*num_uncomputed_blocks_all_waiting_prefills\x18\x19 \x01(\x05R%numUncomputedBlocksAllWaitingPrefills\x12-\n" +
	"\x13num_migrate_in_reqs\x18\x1a \x01(\x05R\x10numMigrateInReqs\x12/\n" +
	"\x14num_migrate_out_reqs\x18\x1b \x01(\x05R\x11numMigrateOutReqs\x12B\n" +
	"\x1enum_available_migrate_in_slots\x18\x1c \x01(\x05R\x1anumAvailableMigrateInSlots\x12D\n" +
	"\x1fnum_available_migrate_out_slots\x18\x1d \x01(\x05R\x1bnumAvailableMigrateOutSlots\x121\n" +
	"\x15num_migrate_in_tokens\x18\x1e \x01(\x05R\x12numMigrateInTokens\x123\n" +
	"\x16num_migrate_out_tokens\x18\x1f \x01(\x05R\x13numMigrateOutTokens\x12D\n" +
	"\x1fnum_available_migrate_in_tokens\x18  \x01(\x05R\x1bnumAvailableMigrateInTokens\x12F\n" +
	" num_available_migrate_out_tokens\x18! \x01(\x05R\x1cnumAvailableMigrateOutTokens\x123\n" +
	"\x16block_ratio_migrate_in\x18\" \x01(\x01R\x13blockRatioMigrateIn\x125\n" +
	"\x17block_ratio_migrate_out\x18# \x01(\x01R\x14blockRatioMigrateOut\x12F\n" +
	" available_block_ratio_migrate_in\x18$ \x01(\x01R\x1cavailableBlockRatioMigrateIn\x12H\n" +
	"!available_block_ratio_migrate_out\x18% \x01(\x01R\x1davailableBlockRatioMigrateOut\x12!\n" +
	"\fprofiling_id\x18& \x01(\x05R\vprofilingId\x12#\n" +
	"\rstep_duration\x18' \x01(\x01R\fstepDuration\x12?\n" +
	"\x1cnum_scheduled_prefill_tokens\x18( \x01(\x05R\x19numScheduledPrefillTokensB\bZ\x06./;cmsb\x06proto3"

var (
	file_llm_gateway_cms_proto_cms_proto_rawDescOnce sync.Once
	file_llm_gateway_cms_proto_cms_proto_rawDescData []byte
)

func file_llm_gateway_cms_proto_cms_proto_rawDescGZIP() []byte {
	file_llm_gateway_cms_proto_cms_proto_rawDescOnce.Do(func() {
		file_llm_gateway_cms_proto_cms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_gateway_cms_proto_cms_proto_rawDesc), len(file_llm_gateway_cms_proto_cms_proto_rawDesc)))
	})
	return file_llm_gateway_cms_proto_cms_proto_rawDescData
}

var file_llm_gateway_cms_proto_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llm_gateway_cms_proto_cms_proto_goTypes = []any{
	(*InstanceMetadata)(nil), // 0: cms.InstanceMetadata
	(*InstanceStatus)(nil),   // 1: cms.InstanceStatus
}
var file_llm_gateway_cms_proto_cms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_gateway_cms_proto_cms_proto_init() }
func file_llm_gateway_cms_proto_cms_proto_init() {
	if File_llm_gateway_cms_proto_cms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_gateway_cms_proto_cms_proto_rawDesc), len(file_llm_gateway_cms_proto_cms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_gateway_cms_proto_cms_proto_goTypes,
		DependencyIndexes: file_llm_gateway_cms_proto_cms_proto_depIdxs,
		MessageInfos:      file_llm_gateway_cms_proto_cms_proto_msgTypes,
	}.Build()
	File_llm_gateway_cms_proto_cms_proto = out.File
	file_llm_gateway_cms_proto_cms_proto_goTypes = nil
	file_llm_gateway_cms_proto_cms_proto_depIdxs = nil
}
