package protocol

import (
	"encoding/json"
	"llm-gateway/pkg/consts"
)

// Chat message role defined by the OpenAI API.
const (
	ChatMessageRoleSystem    = "system"
	ChatMessageRoleUser      = "user"
	ChatMessageRoleAssistant = "assistant"
	ChatMessageRoleFunction  = "function"
	ChatMessageRoleTool      = "tool"
)

const (
	ChatCompletionsPath   = "/v1/chat/completions"
	ChatCompletionsSuffix = "/chat/completions"
)

func IsChatCompletionsURL(url string) bool {
	return len(url) >= len(ChatCompletionsSuffix) && url[len(url)-len(ChatCompletionsSuffix):] == ChatCompletionsSuffix
}

type Hate struct {
	Filtered bool   `json:"filtered"`
	Severity string `json:"severity,omitempty"`
}
type SelfHarm struct {
	Filtered bool   `json:"filtered"`
	Severity string `json:"severity,omitempty"`
}
type Sexual struct {
	Filtered bool   `json:"filtered"`
	Severity string `json:"severity,omitempty"`
}
type Violence struct {
	Filtered bool   `json:"filtered"`
	Severity string `json:"severity,omitempty"`
}

type ContentFilterResults struct {
	Hate     Hate     `json:"hate,omitempty"`
	SelfHarm SelfHarm `json:"self_harm,omitempty"`
	Sexual   Sexual   `json:"sexual,omitempty"`
	Violence Violence `json:"violence,omitempty"`
}

type PromptAnnotation struct {
	PromptIndex          int                  `json:"prompt_index,omitempty"`
	ContentFilterResults ContentFilterResults `json:"content_filter_results,omitempty"`
}

type ImageURLDetail string

const (
	ImageURLDetailHigh ImageURLDetail = "high"
	ImageURLDetailLow  ImageURLDetail = "low"
	ImageURLDetailAuto ImageURLDetail = "auto"
)

type ChatMessageImageURL struct {
	URL    string         `json:"url,omitempty"`
	Detail ImageURLDetail `json:"detail,omitempty"`
}

type ChatMessagePartType string

const (
	ChatMessagePartTypeText     ChatMessagePartType = "text"
	ChatMessagePartTypeImageURL ChatMessagePartType = "image_url"
)

type ChatMessagePart struct {
	Type     ChatMessagePartType  `json:"type,omitempty"`
	Text     string               `json:"text,omitempty"`
	ImageURL *ChatMessageImageURL `json:"image_url,omitempty"`
}

type ChatCompletionMessage struct {
	Role             string `json:"role"`
	Content          string `json:"content"`
	ReasoningContent string `json:"reasoning_content"`
	MultiContent     []ChatMessagePart

	// This property isn't in the official documentation, but it's in
	// the documentation for the official library for python:
	// - https://github.com/openai/openai-python/blob/main/chatml.md
	// - https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
	Name string `json:"name,omitempty"`

	FunctionCall *FunctionCall `json:"function_call,omitempty"`

	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []ToolCall `json:"tool_calls"`

	// For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.
	ToolCallID string `json:"tool_call_id,omitempty"`
}

func (m ChatCompletionMessage) MarshalJSON() ([]byte, error) {
	if m.Content != "" && m.MultiContent != nil {
		return nil, consts.ErrorContentFieldsMisused
	}
	if len(m.MultiContent) > 0 {
		msg := struct {
			Role             string            `json:"role"`
			Content          string            `json:"-"`
			ReasoningContent string            `json:"reasoning_content"`
			MultiContent     []ChatMessagePart `json:"content,omitempty"`
			Name             string            `json:"name,omitempty"`
			FunctionCall     *FunctionCall     `json:"function_call,omitempty"`
			ToolCalls        []ToolCall        `json:"tool_calls"`
			ToolCallID       string            `json:"tool_call_id,omitempty"`
		}(m)
		return json.Marshal(msg)
	}
	msg := struct {
		Role             string            `json:"role"`
		Content          string            `json:"content"`
		ReasoningContent string            `json:"reasoning_content"`
		MultiContent     []ChatMessagePart `json:"-"`
		Name             string            `json:"name,omitempty"`
		FunctionCall     *FunctionCall     `json:"function_call,omitempty"`
		ToolCalls        []ToolCall        `json:"tool_calls"`
		ToolCallID       string            `json:"tool_call_id,omitempty"`
	}(m)
	return json.Marshal(msg)
}

func (m *ChatCompletionMessage) UnmarshalJSON(bs []byte) error {
	msg := struct {
		Role             string `json:"role"`
		Content          string `json:"content"`
		ReasoningContent string `json:"reasoning_content"`
		MultiContent     []ChatMessagePart
		Name             string        `json:"name,omitempty"`
		FunctionCall     *FunctionCall `json:"function_call,omitempty"`
		ToolCalls        []ToolCall    `json:"tool_calls"`
		ToolCallID       string        `json:"tool_call_id,omitempty"`
	}{}
	if err := json.Unmarshal(bs, &msg); err == nil {
		*m = ChatCompletionMessage(msg)
		return nil
	}
	multiMsg := struct {
		Role             string `json:"role"`
		Content          string
		ReasoningContent string            `json:"reasoning_content"`
		MultiContent     []ChatMessagePart `json:"content"`
		Name             string            `json:"name,omitempty"`
		FunctionCall     *FunctionCall     `json:"function_call,omitempty"`
		ToolCalls        []ToolCall        `json:"tool_calls"`
		ToolCallID       string            `json:"tool_call_id,omitempty"`
	}{}
	if err := json.Unmarshal(bs, &multiMsg); err != nil {
		return err
	}
	*m = ChatCompletionMessage(multiMsg)
	return nil
}

type ToolCall struct {
	// Index is not nil only in chat completion chunk object
	Index    *int         `json:"index,omitempty"`
	ID       string       `json:"id"`
	Type     ToolType     `json:"type"`
	Function FunctionCall `json:"function"`
}

type FunctionCall struct {
	Name string `json:"name,omitempty"`
	// call function with arguments in JSON format
	Arguments string `json:"arguments,omitempty"`
}

type ChatCompletionResponseFormatType string

const (
	ChatCompletionResponseFormatTypeJSONObject ChatCompletionResponseFormatType = "json_object"
	ChatCompletionResponseFormatTypeJSONSchema ChatCompletionResponseFormatType = "json_schema"
	ChatCompletionResponseFormatTypeText       ChatCompletionResponseFormatType = "text"
)

type ChatCompletionResponseFormat struct {
	Type       ChatCompletionResponseFormatType        `json:"type,omitempty"`
	JSONSchema *ChatCompletionResponseFormatJSONSchema `json:"json_schema,omitempty"`
}

type ChatCompletionResponseFormatJSONSchema struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Schema      json.Marshaler `json:"schema"`
	Strict      bool           `json:"strict"`
}

// ChatCompletionRequest represents a request structure for chat completion API.
type ChatCompletionRequest struct {
	Model            string                        `json:"model"`
	Messages         []ChatCompletionMessage       `json:"messages"`
	MaxTokens        *int                          `json:"max_tokens,omitempty"`
	Temperature      float32                       `json:"temperature,omitempty"`
	TopP             float32                       `json:"top_p,omitempty"`
	N                int                           `json:"n,omitempty"`
	Stream           bool                          `json:"stream,omitempty"`
	Stop             []string                      `json:"stop,omitempty"`
	PresencePenalty  float32                       `json:"presence_penalty,omitempty"`
	ResponseFormat   *ChatCompletionResponseFormat `json:"response_format,omitempty"`
	Seed             *int                          `json:"seed,omitempty"`
	FrequencyPenalty float32                       `json:"frequency_penalty,omitempty"`
	// LogitBias is must be a token id string (specified by their token ID in the tokenizer), not a word string.
	// incorrect: `"logit_bias":{"You": 6}`, correct: `"logit_bias":{"1639": 6}`
	// refs: https://platform.openai.com/docs/api-reference/chat/create#chat/create-logit_bias
	LogitBias map[string]int `json:"logit_bias,omitempty"`
	// LogProbs indicates whether to return log probabilities of the output tokens or not.
	// If true, returns the log probabilities of each output token returned in the content of message.
	// This option is currently not available on the gpt-4-vision-preview model.
	LogProbs bool `json:"logprobs,omitempty"`
	// TopLogProbs is an integer between 0 and 5 specifying the number of most likely tokens to return at each
	// token position, each with an associated log probability.
	// logprobs must be set to true if this parameter is used.
	TopLogProbs int    `json:"top_logprobs,omitempty"`
	User        string `json:"user,omitempty"`
	// Deprecated: use Tools instead.
	Functions []FunctionDefinition `json:"functions,omitempty"`
	// Deprecated: use ToolChoice instead.
	FunctionCall interface{} `json:"function_call,omitempty"`
	Tools        []Tool      `json:"tools,omitempty"`
	// This can be either a string or an ToolChoice object.
	ToolChoice interface{} `json:"tool_choice,omitempty"`
	// Options for streaming response. Only set this when you set stream: true.
	StreamOptions *StreamOptions `json:"stream_options,omitempty"`
	// Disable the default behavior of parallel tool calls by setting it: false.
	ParallelToolCalls interface{} `json:"parallel_tool_calls,omitempty"`
	// kv transfer params
	KvTransferParams map[string]interface{} `json:"kv_transfer_params,omitempty"`

	// ChatTemplateKwargs provides a way to add non-standard parameters to the request body.
	// Additional kwargs to pass to the template renderer. Will be accessible by the chat template.
	// Such as think mode for qwen3. "chat_template_kwargs": {"enable_thinking": false}
	// https://qwen.readthedocs.io/en/latest/deployment/vllm.html#thinking-non-thinking-modes
	ChatTemplateKwargs map[string]any `json:"chat_template_kwargs,omitempty"`
	ChatCompletionRequestExtensions
}

// ChatCompletionRequestExtensions contains third-party OpenAI API extensions
// (e.g., vendor-specific implementations like vLLM).
type ChatCompletionRequestExtensions struct {
	// GuidedChoice is a vLLM-specific extension that restricts the model's output
	// to one of the predefined string choices provided in this field. This feature
	// is used to constrain the model's responses to a controlled set of options,
	// ensuring predictable and consistent outputs in scenarios where specific
	// choices are required.
	GuidedChoice []string `json:"guided_choice,omitempty"`

	// Sglang PD disaggregation related fields
	Rid           string `json:"rid,omitempty"`            // sglang
	BootStrapHost string `json:"bootstrap_host,omitempty"` // sglang
	BootStrapRoom int    `json:"bootstrap_room,omitempty"` // sglang
}

type StreamOptions struct {
	// If set, an additional chunk will be streamed before the data: [DONE] message.
	// The usage field on this chunk shows the token usage statistics for the entire request,
	// and the choices field will always be an empty array.
	// All other chunks will also include a usage field, but with a null value.
	IncludeUsage           bool `json:"include_usage"`
	IncludeContinuousUsage bool `json:"include_continuous_usage,omitempty"`
}

type ToolType string

const (
	ToolTypeFunction ToolType = "function"
)

type Tool struct {
	Type     ToolType            `json:"type"`
	Function *FunctionDefinition `json:"function,omitempty"`
}

type ToolChoice struct {
	Type     ToolType     `json:"type"`
	Function ToolFunction `json:"function,omitempty"`
}

type ToolFunction struct {
	Name string `json:"name"`
}

type FunctionDefinition struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Strict      bool   `json:"strict,omitempty"`
	// Parameters is an object describing the function.
	// You can pass json.RawMessage to describe the schema,
	// or you can pass in a struct which serializes to the proper JSON schema.
	// The jsonschema package is provided for convenience, but you should
	// consider another specialized library if you require more complex schemas.
	Parameters interface{} `json:"parameters"`
}

// Deprecated: use FunctionDefinition instead.
type FunctionDefine = FunctionDefinition

type TopLogProbs struct {
	Token   string  `json:"token"`
	LogProb float64 `json:"logprob"`
	Bytes   []byte  `json:"bytes,omitempty"`
}

// LogProb represents the probability information for a token.
type LogProb struct {
	Token   string  `json:"token"`
	LogProb float64 `json:"logprob"`
	Bytes   []byte  `json:"bytes,omitempty"` // Omitting the field if it is null
	// TopLogProbs is a list of the most likely tokens and their log probability, at this token position.
	// In rare cases, there may be fewer than the number of requested top_logprobs returned.
	TopLogProbs []TopLogProbs `json:"top_logprobs"`
}

// LogProbs is the top-level structure containing the log probability information.
type LogProbs struct {
	// Content is a list of message content tokens with log probability information.
	Content []LogProb `json:"content"`
}

type FinishReason string

const (
	FinishReasonStop          FinishReason = "stop"
	FinishReasonLength        FinishReason = "length"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonToolCalls     FinishReason = "tool_calls"
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonNull          FinishReason = "null"
	FinishReasonAbort         FinishReason = "abort"
)

func (r FinishReason) MarshalJSON() ([]byte, error) {
	if r == FinishReasonNull || r == "" {
		return []byte(`""`), nil
	}
	return []byte(`"` + string(r) + `"`), nil // best effort to not break future API changes
}

type ChatCompletionChoice struct {
	Index   int                   `json:"index"`
	Message ChatCompletionMessage `json:"message"`
	// FinishReason
	// stop: API returned complete message,
	// or a message terminated by one of the stop sequences provided via the stop parameter
	// length: Incomplete model output due to max_tokens parameter or token limit
	// function_call: The model decided to call a function
	// content_filter: Omitted content due to a flag from our content filters
	// abort: Request was aborted
	// null: API response still in progress or incomplete
	FinishReason FinishReason `json:"finish_reason"`
	StopReason   interface{}  `json:"stop_reason,omitempty"`
	LogProbs     *LogProbs    `json:"logprobs,omitempty"`
}

// ChatCompletionResponse represents a response structure for chat completion API.
type ChatCompletionResponse struct {
	ID                string                 `json:"id"`
	Object            string                 `json:"object"`
	Created           int64                  `json:"created"`
	Model             string                 `json:"model"`
	SystemFingerprint string                 `json:"system_fingerprint"`
	Choices           []ChatCompletionChoice `json:"choices"`
	Usage             *Usage                 `json:"usage"`
	KvTransferParams  map[string]interface{} `json:"kv_transfer_params,omitempty"`
	//PromptLogprobs    string                 `json:"prompt_logprobs,omitempty"` // vllm specific
}

////////////////////// streaming chat response ////////////////////////

type ChatCompletionStreamChoiceDelta struct {
	Role             string        `json:"role,omitempty"`
	Content          string        `json:"content"`
	ReasoningContent string        `json:"reasoning_content"`
	ToolCalls        []ToolCall    `json:"tool_calls"`
	FunctionCall     *FunctionCall `json:"function_call,omitempty"`
}

type ChatCompletionStreamChoice struct {
	Index        int                             `json:"index"`
	Delta        ChatCompletionStreamChoiceDelta `json:"delta"`
	FinishReason FinishReason                    `json:"finish_reason"`
	LogProbs     *TopLogProbs                    `json:"logprobs,omitempty"`
	//ContentFilterResults ContentFilterResults            `json:"content_filter_results,omitempty"`
}

type PromptFilterResult struct {
	Index                int                  `json:"index"`
	ContentFilterResults ContentFilterResults `json:"content_filter_results,omitempty"`
}

type ChatCompletionStreamResponse struct {
	ID                string                       `json:"id"`
	Choices           []ChatCompletionStreamChoice `json:"choices"`
	Created           int64                        `json:"created"`
	Model             string                       `json:"model"`
	SystemFingerprint string                       `json:"system_fingerprint"`
	Object            string                       `json:"object"`
	Usage             *Usage                       `json:"usage,omitempty"`
	PromptAnnotations []PromptAnnotation           `json:"prompt_annotations,omitempty"`
	//PromptFilterResults []PromptFilterResult         `json:"prompt_filter_results,omitempty"`
	// An optional field that will only be present when you set stream_options: {"include_usage": true} in your request.
	// When present, it contains a null value except for the last chunk which contains the token usage statistics
	// for the entire request.
}

// Clone creates a deep copy of the ChatCompletionRequest.
func (r *ChatCompletionRequest) Clone() *ChatCompletionRequest {
	if r == nil {
		return nil
	}

	// Direct value copy for all primitive fields (compiler optimizes to efficient memcpy)
	cloned := &ChatCompletionRequest{
		Model:             r.Model,
		Temperature:       r.Temperature,
		TopP:              r.TopP,
		N:                 r.N,
		Stream:            r.Stream,
		PresencePenalty:   r.PresencePenalty,
		FrequencyPenalty:  r.FrequencyPenalty,
		LogProbs:          r.LogProbs,
		TopLogProbs:       r.TopLogProbs,
		User:              r.User,
		FunctionCall:      r.FunctionCall,
		ToolChoice:        r.ToolChoice,
		ParallelToolCalls: r.ParallelToolCalls,
	}

	// Copy embedded ChatCompletionRequestExtensions fields
	cloned.Rid = r.Rid
	cloned.BootStrapHost = r.BootStrapHost
	cloned.BootStrapRoom = r.BootStrapRoom

	// Deep copy MaxTokens pointer
	if r.MaxTokens != nil {
		val := *r.MaxTokens
		cloned.MaxTokens = &val
	}

	// Deep copy Messages slice with pre-allocated capacity
	if len(r.Messages) > 0 {
		cloned.Messages = make([]ChatCompletionMessage, len(r.Messages))
		for i := range r.Messages {
			cloned.Messages[i] = cloneChatCompletionMessage(&r.Messages[i])
		}
	}

	// Deep copy Stop slice (compiler optimizes copy() to memmove for string slices)
	if len(r.Stop) > 0 {
		cloned.Stop = make([]string, len(r.Stop))
		copy(cloned.Stop, r.Stop)
	}

	// Deep copy ResponseFormat pointer with nested JSONSchema
	if r.ResponseFormat != nil {
		cloned.ResponseFormat = &ChatCompletionResponseFormat{
			Type: r.ResponseFormat.Type,
		}
		if r.ResponseFormat.JSONSchema != nil {
			cloned.ResponseFormat.JSONSchema = &ChatCompletionResponseFormatJSONSchema{
				Name:        r.ResponseFormat.JSONSchema.Name,
				Description: r.ResponseFormat.JSONSchema.Description,
				Schema:      r.ResponseFormat.JSONSchema.Schema,
				Strict:      r.ResponseFormat.JSONSchema.Strict,
			}
		}
	}

	// Deep copy Seed pointer (dereference-and-repoint pattern)
	if r.Seed != nil {
		val := *r.Seed
		cloned.Seed = &val
	}

	// Deep copy LogitBias map with pre-allocated capacity to avoid rehashing
	if len(r.LogitBias) > 0 {
		cloned.LogitBias = make(map[string]int, len(r.LogitBias))
		for k, v := range r.LogitBias {
			cloned.LogitBias[k] = v
		}
	}

	// Deep copy Functions slice (deprecated field, kept for backward compatibility)
	if len(r.Functions) > 0 {
		cloned.Functions = make([]FunctionDefinition, len(r.Functions))
		for i := range r.Functions {
			cloned.Functions[i] = cloneFunctionDefinition(&r.Functions[i])
		}
	}

	// Deep copy Tools slice with nested Function pointers
	if len(r.Tools) > 0 {
		cloned.Tools = make([]Tool, len(r.Tools))
		for i := range r.Tools {
			cloned.Tools[i] = Tool{Type: r.Tools[i].Type}
			if r.Tools[i].Function != nil {
				funcDef := cloneFunctionDefinition(r.Tools[i].Function)
				cloned.Tools[i].Function = &funcDef
			}
		}
	}

	// Deep copy StreamOptions pointer
	if r.StreamOptions != nil {
		cloned.StreamOptions = &StreamOptions{
			IncludeUsage:           r.StreamOptions.IncludeUsage,
			IncludeContinuousUsage: r.StreamOptions.IncludeContinuousUsage,
		}
	}

	// Shallow copy KvTransferParams map values (interface{} deep copy requires reflection)
	if len(r.KvTransferParams) > 0 {
		cloned.KvTransferParams = make(map[string]interface{}, len(r.KvTransferParams))
		for k, v := range r.KvTransferParams {
			cloned.KvTransferParams[k] = v
		}
	}

	// Shallow copy ChatTemplateKwargs map values
	if len(r.ChatTemplateKwargs) > 0 {
		cloned.ChatTemplateKwargs = make(map[string]any, len(r.ChatTemplateKwargs))
		for k, v := range r.ChatTemplateKwargs {
			cloned.ChatTemplateKwargs[k] = v
		}
	}

	// Deep copy GuidedChoice slice
	if len(r.GuidedChoice) > 0 {
		cloned.GuidedChoice = make([]string, len(r.GuidedChoice))
		copy(cloned.GuidedChoice, r.GuidedChoice)
	}

	return cloned
}

// cloneChatCompletionMessage performs deep copy of a single message structure.
// Recursively clones all nested slices and pointer fields to ensure complete isolation.
func cloneChatCompletionMessage(m *ChatCompletionMessage) ChatCompletionMessage {
	cloned := ChatCompletionMessage{
		Role:             m.Role,
		Content:          m.Content,
		ReasoningContent: m.ReasoningContent,
		Name:             m.Name,
		ToolCallID:       m.ToolCallID,
	}

	// Deep copy MultiContent slice with nested ImageURL pointers
	if len(m.MultiContent) > 0 {
		cloned.MultiContent = make([]ChatMessagePart, len(m.MultiContent))
		for i := range m.MultiContent {
			cloned.MultiContent[i] = ChatMessagePart{
				Type: m.MultiContent[i].Type,
				Text: m.MultiContent[i].Text,
			}
			if m.MultiContent[i].ImageURL != nil {
				cloned.MultiContent[i].ImageURL = &ChatMessageImageURL{
					URL:    m.MultiContent[i].ImageURL.URL,
					Detail: m.MultiContent[i].ImageURL.Detail,
				}
			}
		}
	}

	// Deep copy FunctionCall pointer
	if m.FunctionCall != nil {
		cloned.FunctionCall = &FunctionCall{
			Name:      m.FunctionCall.Name,
			Arguments: m.FunctionCall.Arguments,
		}
	}

	// Deep copy ToolCalls slice with nested Function and Index pointer
	if len(m.ToolCalls) > 0 {
		cloned.ToolCalls = make([]ToolCall, len(m.ToolCalls))
		for i := range m.ToolCalls {
			cloned.ToolCalls[i] = ToolCall{
				ID:   m.ToolCalls[i].ID,
				Type: m.ToolCalls[i].Type,
				Function: FunctionCall{
					Name:      m.ToolCalls[i].Function.Name,
					Arguments: m.ToolCalls[i].Function.Arguments,
				},
			}
			if m.ToolCalls[i].Index != nil {
				val := *m.ToolCalls[i].Index
				cloned.ToolCalls[i].Index = &val
			}
		}
	}

	return cloned
}

// cloneFunctionDefinition performs deep copy of function definition.
func cloneFunctionDefinition(f *FunctionDefinition) FunctionDefinition {
	return FunctionDefinition{
		Name:        f.Name,
		Description: f.Description,
		Strict:      f.Strict,
		Parameters:  f.Parameters, // Shallow copy (safe for typical immutable schemas)
	}
}

// Setter methods for ChatCompletionRequest to support unified field assignment

func (r *ChatCompletionRequest) SetKvTransferParams(params map[string]interface{}) {
	r.KvTransferParams = params
}

func (r *ChatCompletionRequest) SetRid(rid string) {
	r.Rid = rid
}

func (r *ChatCompletionRequest) SetBootStrapHost(host string) {
	r.BootStrapHost = host
}

func (r *ChatCompletionRequest) SetBootStrapRoom(room int) {
	r.BootStrapRoom = room
}

func (r *ChatCompletionRequest) SetMaxTokens(maxTokens int) {
	r.MaxTokens = &maxTokens
}

func (r *ChatCompletionRequest) SetStream(stream bool) {
	r.Stream = stream
}
