apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: prefill
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 1
    workerTemplate:
      spec:
        imagePullSecrets:
          - name: aliyun-registry-secret
        terminationGracePeriodSeconds: 30
        containers:
        - name: vllm
          image: beijing-pooling-registry-vpc.cn-beijing.cr.aliyuncs.com/llumnix/llumnix-dev:llumnix-vllm-20260130-105854
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RAWIO
            runAsGroup: 0
            runAsUser: 0
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
          args:
            - |-

             #################
             # RUN vLLM prefill worker
             #################
             START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))

             # --data-parallel-hybrid-lb: Use exernal load balancing across nodes, and internal load balancing within a node
             # --enable-expert-parallel: Use TPxDP in attention, EP in MoE layers
             # --async-scheduling: Reduce white space between engine steps
             # --enable-dbo: Dual batch overlap (DBO) overlaps compute with collective communication.
             # --enable-eplb:  Expert-parallel load balancing reduces EP load imbalance by replicating heavily-used experts Performance-memory tradeoff: on DeepSeekV3 eplb uses an extra 2GB per redundant expert per GPU Divisibility constraint: num_routed_experts (256 for DSv3) + num_redundant_experts must be divisible by the number of GPUs.

             exec vllm serve \
                Qwen/Qwen3-235B-A22B-FP8 \
                --port 8000 \
                --trust-remote-code \
                --enable-expert-parallel \
                --tensor-parallel-size $TP_SIZE \
                --data-parallel-size $((LWS_GROUP_SIZE * DP_SIZE_LOCAL)) \
                --data-parallel-size-local $DP_SIZE_LOCAL \
                --data-parallel-address ${LWS_LEADER_ADDRESS} \
                --data-parallel-rpc-port 5555 \
                --data-parallel-start-rank $START_RANK \
                --async-scheduling \
                --kv-transfer-config '{"kv_connector":"MooncakeConnector","kv_role":"kv_producer", "kv_connector_module_path":"mooncake.mooncake_connector_v1"}' \
                --gpu-memory-utilization 0.8

          env:
          # Redis configuration for Llumnix
          - name: LLUMNIX_CMS_REDIS_ADDRESS
            value: "redis"
          - name: LLUMNIX_CMS_REDIS_PORT
            value: "6379"
          - name: LLUMNIX_CMS_REDIS_USERNAME
            value: ""
          - name: LLUMNIX_CMS_REDIS_PASSWORD
            value: ""
          - name: VLLM_ENABLE_LLUMNIX
            value: "1"
          - name: LLUMNIX_ENABLE_MIGRATION
            value: "0"

          # download models
          - name: VLLM_USE_MODELSCOPE
            value: "true"

          - name: DP_SIZE_LOCAL
            value: "1"
          - name: TP_SIZE
            value: "8"
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: GLOO_SOCKET_IFNAME
            value: eth0
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          # Use cache directories from the mounted volume under one easy to mount
          # root directory.
          - name: CUDA_CACHE_PATH
            value: /var/cache/vllm/cuda
          - name: CCACHE_DIR
            value: /var/cache/vllm/ccache
          - name: VLLM_CACHE_ROOT
            value: /var/cache/vllm/vllm
          - name: FLASHINFER_WORKSPACE_BASE
            value: /var/cache/vllm/flashinfer
          # HuggingFace is likely to be quite a bit larger, give it its own cache
          - name: HF_HUB_CACHE
            value: /var/cache/huggingface

          ports:
          - containerPort: 8000
            name: metrics
            protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 0
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 2700
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              ephemeral-storage: 512Gi
              memory: 512Gi
              nvidia.com/gpu: "8"
            requests:
              cpu: "64"
              ephemeral-storage: 512Gi
              memory: 512Gi
              nvidia.com/gpu: "8"
        - name: discovery
          image: beijing-pooling-registry-vpc.cn-beijing.cr.aliyuncs.com/llumnix/llumnix-dev:discovery-20260226-170427
          command:
            - /bin/bash
            - -c
          args:
            - |-
              cd /discovery && \
              exec python3 -m discovery.discovery \
              --role prefill \
              --pod_name $(POD_NAME) \
              --entrypoint_ip $(POD_IP) \
              --entrypoint_port 8000 \
              --kv_transfer_ip $(POD_IP) \
              --kv_transfer_port 28000 \
              --dp_size_local 1 \
              --redis_address redis \
              --redis_port 6379
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
