// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: llm-gateway/llumlet/proto/llumlet_server.proto

package llumlet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Llumlet_Migrate_FullMethodName = "/llumlet.Llumlet/Migrate"
	Llumlet_Abort_FullMethodName   = "/llumlet.Llumlet/Abort"
)

// LlumletClient is the client API for Llumlet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlumletClient interface {
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	Abort(ctx context.Context, in *AbortRequests, opts ...grpc.CallOption) (*AbortResponse, error)
}

type llumletClient struct {
	cc grpc.ClientConnInterface
}

func NewLlumletClient(cc grpc.ClientConnInterface) LlumletClient {
	return &llumletClient{cc}
}

func (c *llumletClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, Llumlet_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llumletClient) Abort(ctx context.Context, in *AbortRequests, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, Llumlet_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlumletServer is the server API for Llumlet service.
// All implementations must embed UnimplementedLlumletServer
// for forward compatibility.
type LlumletServer interface {
	Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	Abort(context.Context, *AbortRequests) (*AbortResponse, error)
	mustEmbedUnimplementedLlumletServer()
}

// UnimplementedLlumletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlumletServer struct{}

func (UnimplementedLlumletServer) Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedLlumletServer) Abort(context.Context, *AbortRequests) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedLlumletServer) mustEmbedUnimplementedLlumletServer() {}
func (UnimplementedLlumletServer) testEmbeddedByValue()                 {}

// UnsafeLlumletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlumletServer will
// result in compilation errors.
type UnsafeLlumletServer interface {
	mustEmbedUnimplementedLlumletServer()
}

func RegisterLlumletServer(s grpc.ServiceRegistrar, srv LlumletServer) {
	// If the following call pancis, it indicates UnimplementedLlumletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Llumlet_ServiceDesc, srv)
}

func _Llumlet_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlumletServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Llumlet_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlumletServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Llumlet_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlumletServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Llumlet_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlumletServer).Abort(ctx, req.(*AbortRequests))
	}
	return interceptor(ctx, in, info, handler)
}

// Llumlet_ServiceDesc is the grpc.ServiceDesc for Llumlet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Llumlet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llumlet.Llumlet",
	HandlerType: (*LlumletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _Llumlet_Migrate_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _Llumlet_Abort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm-gateway/llumlet/proto/llumlet_server.proto",
}
