// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: llm-gateway/llumlet/proto/llumlet_server.proto

package llumlet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SrcEngineId        string                 `protobuf:"bytes,1,opt,name=src_engine_id,json=srcEngineId,proto3" json:"src_engine_id,omitempty"`
	DstEngineId        string                 `protobuf:"bytes,2,opt,name=dst_engine_id,json=dstEngineId,proto3" json:"dst_engine_id,omitempty"`
	DstEngineIp        string                 `protobuf:"bytes,3,opt,name=dst_engine_ip,json=dstEngineIp,proto3" json:"dst_engine_ip,omitempty"`
	DstEnginePort      int32                  `protobuf:"varint,4,opt,name=dst_engine_port,json=dstEnginePort,proto3" json:"dst_engine_port,omitempty"`
	MigrationType      string                 `protobuf:"bytes,5,opt,name=migration_type,json=migrationType,proto3" json:"migration_type,omitempty"`
	MigrationReqPolicy string                 `protobuf:"bytes,6,opt,name=migration_req_policy,json=migrationReqPolicy,proto3" json:"migration_req_policy,omitempty"`
	// Types that are valid to be assigned to MigrationValue:
	//
	//	*MigrateRequest_NumReqs
	//	*MigrateRequest_NumTokens
	//	*MigrateRequest_BlockRatio
	MigrationValue isMigrateRequest_MigrationValue `protobuf_oneof:"migration_value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescGZIP(), []int{0}
}

func (x *MigrateRequest) GetSrcEngineId() string {
	if x != nil {
		return x.SrcEngineId
	}
	return ""
}

func (x *MigrateRequest) GetDstEngineId() string {
	if x != nil {
		return x.DstEngineId
	}
	return ""
}

func (x *MigrateRequest) GetDstEngineIp() string {
	if x != nil {
		return x.DstEngineIp
	}
	return ""
}

func (x *MigrateRequest) GetDstEnginePort() int32 {
	if x != nil {
		return x.DstEnginePort
	}
	return 0
}

func (x *MigrateRequest) GetMigrationType() string {
	if x != nil {
		return x.MigrationType
	}
	return ""
}

func (x *MigrateRequest) GetMigrationReqPolicy() string {
	if x != nil {
		return x.MigrationReqPolicy
	}
	return ""
}

func (x *MigrateRequest) GetMigrationValue() isMigrateRequest_MigrationValue {
	if x != nil {
		return x.MigrationValue
	}
	return nil
}

func (x *MigrateRequest) GetNumReqs() int64 {
	if x != nil {
		if x, ok := x.MigrationValue.(*MigrateRequest_NumReqs); ok {
			return x.NumReqs
		}
	}
	return 0
}

func (x *MigrateRequest) GetNumTokens() int64 {
	if x != nil {
		if x, ok := x.MigrationValue.(*MigrateRequest_NumTokens); ok {
			return x.NumTokens
		}
	}
	return 0
}

func (x *MigrateRequest) GetBlockRatio() float32 {
	if x != nil {
		if x, ok := x.MigrationValue.(*MigrateRequest_BlockRatio); ok {
			return x.BlockRatio
		}
	}
	return 0
}

type isMigrateRequest_MigrationValue interface {
	isMigrateRequest_MigrationValue()
}

type MigrateRequest_NumReqs struct {
	NumReqs int64 `protobuf:"varint,7,opt,name=num_reqs,json=numReqs,proto3,oneof"`
}

type MigrateRequest_NumTokens struct {
	NumTokens int64 `protobuf:"varint,8,opt,name=num_tokens,json=numTokens,proto3,oneof"`
}

type MigrateRequest_BlockRatio struct {
	BlockRatio float32 `protobuf:"fixed32,9,opt,name=block_ratio,json=blockRatio,proto3,oneof"`
}

func (*MigrateRequest_NumReqs) isMigrateRequest_MigrationValue() {}

func (*MigrateRequest_NumTokens) isMigrateRequest_MigrationValue() {}

func (*MigrateRequest_BlockRatio) isMigrateRequest_MigrationValue() {}

type MigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AbortRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestIds    []string               `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequests) Reset() {
	*x = AbortRequests{}
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequests) ProtoMessage() {}

func (x *AbortRequests) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequests.ProtoReflect.Descriptor instead.
func (*AbortRequests) Descriptor() ([]byte, []int) {
	return file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescGZIP(), []int{2}
}

func (x *AbortRequests) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescGZIP(), []int{3}
}

func (x *AbortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_llm_gateway_llumlet_proto_llumlet_server_proto protoreflect.FileDescriptor

const file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDesc = "" +
	"\n" +
	".llm-gateway/llumlet/proto/llumlet_server.proto\x12\allumlet\"\xf1\x02\n" +
	"\x0eMigrateRequest\x12\"\n" +
	"\rsrc_engine_id\x18\x01 \x01(\tR\vsrcEngineId\x12\"\n" +
	"\rdst_engine_id\x18\x02 \x01(\tR\vdstEngineId\x12\"\n" +
	"\rdst_engine_ip\x18\x03 \x01(\tR\vdstEngineIp\x12&\n" +
	"\x0fdst_engine_port\x18\x04 \x01(\x05R\rdstEnginePort\x12%\n" +
	"\x0emigration_type\x18\x05 \x01(\tR\rmigrationType\x120\n" +
	"\x14migration_req_policy\x18\x06 \x01(\tR\x12migrationReqPolicy\x12\x1b\n" +
	"\bnum_reqs\x18\a \x01(\x03H\x00R\anumReqs\x12\x1f\n" +
	"\n" +
	"num_tokens\x18\b \x01(\x03H\x00R\tnumTokens\x12!\n" +
	"\vblock_ratio\x18\t \x01(\x02H\x00R\n" +
	"blockRatioB\x11\n" +
	"\x0fmigration_value\"E\n" +
	"\x0fMigrateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\rAbortRequests\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\"C\n" +
	"\rAbortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x84\x01\n" +
	"\aLlumlet\x12>\n" +
	"\aMigrate\x12\x17.llumlet.MigrateRequest\x1a\x18.llumlet.MigrateResponse\"\x00\x129\n" +
	"\x05Abort\x12\x16.llumlet.AbortRequests\x1a\x16.llumlet.AbortResponse\"\x00B\fZ\n" +
	"./;llumletb\x06proto3"

var (
	file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescOnce sync.Once
	file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescData []byte
)

func file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescGZIP() []byte {
	file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescOnce.Do(func() {
		file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDesc), len(file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDesc)))
	})
	return file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDescData
}

var file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_gateway_llumlet_proto_llumlet_server_proto_goTypes = []any{
	(*MigrateRequest)(nil),  // 0: llumlet.MigrateRequest
	(*MigrateResponse)(nil), // 1: llumlet.MigrateResponse
	(*AbortRequests)(nil),   // 2: llumlet.AbortRequests
	(*AbortResponse)(nil),   // 3: llumlet.AbortResponse
}
var file_llm_gateway_llumlet_proto_llumlet_server_proto_depIdxs = []int32{
	0, // 0: llumlet.Llumlet.Migrate:input_type -> llumlet.MigrateRequest
	2, // 1: llumlet.Llumlet.Abort:input_type -> llumlet.AbortRequests
	1, // 2: llumlet.Llumlet.Migrate:output_type -> llumlet.MigrateResponse
	3, // 3: llumlet.Llumlet.Abort:output_type -> llumlet.AbortResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_gateway_llumlet_proto_llumlet_server_proto_init() }
func file_llm_gateway_llumlet_proto_llumlet_server_proto_init() {
	if File_llm_gateway_llumlet_proto_llumlet_server_proto != nil {
		return
	}
	file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes[0].OneofWrappers = []any{
		(*MigrateRequest_NumReqs)(nil),
		(*MigrateRequest_NumTokens)(nil),
		(*MigrateRequest_BlockRatio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDesc), len(file_llm_gateway_llumlet_proto_llumlet_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_gateway_llumlet_proto_llumlet_server_proto_goTypes,
		DependencyIndexes: file_llm_gateway_llumlet_proto_llumlet_server_proto_depIdxs,
		MessageInfos:      file_llm_gateway_llumlet_proto_llumlet_server_proto_msgTypes,
	}.Build()
	File_llm_gateway_llumlet_proto_llumlet_server_proto = out.File
	file_llm_gateway_llumlet_proto_llumlet_server_proto_goTypes = nil
	file_llm_gateway_llumlet_proto_llumlet_server_proto_depIdxs = nil
}
