ARG BASE_IMAGE=tongyi-duanwu-registry.cn-beijing.cr.aliyuncs.com/dashscope/dashllm:deepep_cp312_test_v1_deepep_111
FROM ${BASE_IMAGE}

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . ./llumnix

RUN cd llumnix && \
    pip install --no-cache-dir setuptools_scm grpcio-tools==1.71.0 && \
    make proto && \
    pip install .[vllm]

RUN if [ -d "./llumnix/dist" ]; then \
        find ./llumnix/dist -name "*.whl" -type f -exec pip install {} \; || echo "No .whl files found"; \
    fi

RUN rm -rf llumnix

CMD ["bash"]
