name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  go-ut:
    name: Go Unit Tests
    uses: ./.github/workflows/ut-gateway-and-scheduler.yml
    secrets: inherit

  llumnix-ut:
    name: Python llumnix Unit Tests
    uses: ./.github/workflows/ut-llumnix.yml
    secrets: inherit

  discovery-ut:
    name: Python discovery Unit Tests
    uses: ./.github/workflows/ut-discovery.yml
    secrets: inherit

  # docs-build:
  #   name: Build Documentation
  #   uses: ./.github/workflows/docs-build.yml

  all-pr-tests:
    name: All PR Tests
    runs-on: [self-hosted, cpu]
    needs:
      - go-ut
      - llumnix-ut
      - discovery-ut
      - docs-build
    steps:
      - name: All tests passed
        run: echo "All tests passed!"

